import type { PhaseReport } from "./phase-report.js";
import {
  extractRiskJustification,
  parseRiskLevel,
  type RiskLevel,
} from "./tools/github.js";

/**
 * Picks the session output used for the yolo risk assessment.
 *
 * Hook-retry sessions only fix the commit-hook failure and rarely restate the
 * risk, so prefer the most recent session output that actually carries a risk
 * assessment, falling back to the last session when none do.
 */
export function resolveYoloRiskSourceOutput(
  sessions: readonly { outputText: string }[],
): string {
  const withRisk = [...sessions]
    .reverse()
    .find((session) => parseRiskLevel(session.outputText));
  return (
    withRisk?.outputText ?? sessions[sessions.length - 1]?.outputText ?? ""
  );
}

export function resolveYoloRiskAssessment(
  phaseReport: PhaseReport | undefined,
  outputText: string,
): { riskLevel: RiskLevel; riskJustification: string } {
  if (phaseReport?.riskLevel && phaseReport.riskJustification) {
    return {
      riskLevel: phaseReport.riskLevel,
      riskJustification: phaseReport.riskJustification,
    };
  }

  const parsedRiskLevel = parseRiskLevel(outputText);
  if (!parsedRiskLevel) {
    console.warn(
      "Could not parse risk level from yolo output; defaulting to medium.",
    );
  }
  return {
    riskLevel: parsedRiskLevel ?? "medium",
    riskJustification:
      extractRiskJustification(outputText) ??
      "Risk assessment generated by the yolo agent.",
  };
}
