import {
  YOLO_MODEL,
  buildPhaseSystemPrompt,
  loadAgentConfig,
  loadAgentEnv,
  parseRepository,
} from "./config.js";
import {
  checkoutExistingBranch,
  createAndCheckoutBranch,
  resolveYoloBranchName,
} from "./git/branch.js";
import {
  commitAndPushBranch,
  createPullRequest,
  findOpenPullRequestForBranch,
} from "./git/pr.js";
import { buildAgentPrBody } from "./pr-body.js";
import { reportPhaseFailure } from "./report-failure.js";
import {
  appendRunFrictionStepSummary,
  createRunFrictionCollector,
} from "./run-friction.js";
import { runAgentMain, runAgentSession } from "./runtime.js";
import { runAgentPhase } from "./lifecycle.js";
import { safeFormatUsageMarkdown } from "./gha-log.js";
import {
  addLabelToIssue,
  AGENT_COMMENT_MARKERS,
  buildRunUrl,
  createOctokit,
  ensureLabel,
  extractRiskJustification,
  findPlanCommentUrl,
  manageRiskLabels,
  parseRiskLevel,
  postComment,
  prependAgentMarker,
  readComments,
  readIssue,
} from "./tools/github.js";
import { createAgentTools } from "./tools/index.js";
import { withReportRunFrictionTool } from "./tools/run-friction-tool.js";
import {
  appendSubmitPhaseReportTool,
  createPhaseReportTracker,
  formatPhaseCompletionMarkdown,
  formatPhaseReportForPr,
  type PhaseReport,
} from "./phase-report.js";
import type { AgentSessionResult } from "./runtime.js";
import type { RunFrictionCollector } from "./run-friction.js";

async function postYoloIssueComment(
  octokit: ReturnType<typeof createOctokit>,
  owner: string,
  repo: string,
  issueNumber: number,
  params: {
    riskLevel: string;
    riskJustification: string;
    prLine: string;
    phaseReport: PhaseReport | undefined;
    session: AgentSessionResult;
    runFriction: RunFrictionCollector;
  },
): Promise<void> {
  const implementComment = [
    `## Agent Implementation`,
    "",
    `**Risk score:** ${params.riskLevel} — ${params.riskJustification}`,
    "",
    params.prLine,
    "",
    formatPhaseCompletionMarkdown({
      phase: "yolo",
      phaseReport: params.phaseReport,
      sessionUsage: params.session.usage,
      sessionId: params.session.sessionId,
      modelId: params.session.modelId,
      iterations: params.session.iterations,
      toolCallsCount: params.session.toolCallsCount,
      runFriction: params.runFriction,
    }),
  ].join("\n\n");

  await postComment(
    octokit,
    owner,
    repo,
    issueNumber,
    prependAgentMarker(implementComment, AGENT_COMMENT_MARKERS.yolo),
  );
}

async function main() {
  const env = loadAgentEnv();
  const config = loadAgentConfig();
  const { owner, repo } = parseRepository(env.GITHUB_REPOSITORY);
  const octokit = createOctokit(env.GITHUB_TOKEN);

  try {
    const issue = await readIssue(octokit, owner, repo, env.ISSUE_NUMBER);

    const branch = resolveYoloBranchName(
      env.ISSUE_NUMBER,
      issue.title,
      env.AGENT_BRANCH,
      config.git.branch_prefix,
    );
    if (env.AGENT_BRANCH) {
      await checkoutExistingBranch(branch);
    } else {
      await createAndCheckoutBranch(branch, config.git.base_branch);
    }

    const runFriction = createRunFrictionCollector();
    const phaseReportTracker = createPhaseReportTracker();
    const tools = await withReportRunFrictionTool(
      await appendSubmitPhaseReportTool(
        await createAgentTools(octokit, owner, repo, env.ISSUE_NUMBER),
        phaseReportTracker,
      ),
      runFriction,
    );

    const session = await runAgentSession({
      phase: "yolo",
      modelId: YOLO_MODEL,
      systemPrompt: buildPhaseSystemPrompt("yolo", config),
      tools,
      runFriction,
      sessionMetadata: {
        phase: "yolo",
        issueNumber: env.ISSUE_NUMBER,
        repository: env.GITHUB_REPOSITORY,
        branch,
      },
      prompt: `Implement issue #${env.ISSUE_NUMBER}: ${issue.title}

Issue body (implementation instructions):
${issue.body ?? "(empty)"}

Repository: ${env.GITHUB_REPOSITORY}
Branch: ${branch}`,
    });

    appendRunFrictionStepSummary(runFriction, "yolo");

    const phaseReport = phaseReportTracker.report;
    const phaseReportMarkdown = phaseReport
      ? formatPhaseReportForPr(phaseReport)
      : undefined;

    const parsedRiskLevel = parseRiskLevel(session.outputText);
    if (!parsedRiskLevel) {
      console.warn(
        "Could not parse risk level from yolo output; defaulting to medium.",
      );
    }
    const riskLevel = parsedRiskLevel ?? "medium";
    const riskJustification =
      extractRiskJustification(session.outputText) ??
      "Risk assessment generated by the yolo agent.";

    const pushResult = await commitAndPushBranch(
      branch,
      `feat: implement issue #${env.ISSUE_NUMBER} — ${issue.title}`,
    );

    if (pushResult.status === "noChanges") {
      const existingPr = await findOpenPullRequestForBranch(branch);
      const prLine = existingPr
        ? `No new commit was needed: the branch \`${branch}\` already contains the intended changes. Open pull request [#${existingPr.number}](${existingPr.url}).`
        : `No new commit was needed: the branch \`${branch}\` already matches the working tree (no open PR found for this head).`;

      await postYoloIssueComment(octokit, owner, repo, env.ISSUE_NUMBER, {
        riskLevel,
        riskJustification,
        prLine,
        phaseReport,
        session,
        runFriction,
      });

      if (existingPr) {
        try {
          await manageRiskLabels(
            octokit,
            owner,
            repo,
            env.ISSUE_NUMBER,
            riskLevel,
          );
          await manageRiskLabels(
            octokit,
            owner,
            repo,
            existingPr.number,
            riskLevel,
          );
        } catch (error) {
          console.warn("Failed to manage risk labels:", error);
        }
      }

      console.log(
        `\nYolo completed with no changes on branch ${branch}${existingPr ? ` (PR #${existingPr.number})` : ""}`,
      );
      return;
    }

    const comments = await readComments(octokit, owner, repo, env.ISSUE_NUMBER);

    const usageSection = safeFormatUsageMarkdown(session.usage, {
      heading: "### Usage (yolo run)",
      sessionId: session.sessionId,
      modelId: session.modelId,
      iterations: session.iterations,
      toolCallsCount: session.toolCallsCount,
    });

    const pr = await createPullRequest(
      issue.title,
      buildAgentPrBody({
        issueNumber: env.ISSUE_NUMBER,
        issueTitle: issue.title,
        issueUrl: issue.html_url,
        planCommentUrl: findPlanCommentUrl(comments),
        usageMarkdown: usageSection,
        riskLevel,
        riskJustification,
        phaseReportMarkdown,
      }),
      branch,
      config.git.pr_target,
    );

    await addLabelToIssue(octokit, owner, repo, pr.number, "agent-pr");

    const runUrl = buildRunUrl();
    const prOpenedBody = `PR opened by this run — ${runUrl ? `[View in GitHub Actions](${runUrl})` : "run URL unavailable"}`;
    await postComment(
      octokit,
      owner,
      repo,
      pr.number,
      prependAgentMarker(prOpenedBody, AGENT_COMMENT_MARKERS.prOpened),
    );

    try {
      await ensureLabel(octokit, owner, repo, "agent-waiting-human", {
        color: "f9d0c4",
        description: "Waiting for human decision on this issue.",
      });
      await addLabelToIssue(
        octokit,
        owner,
        repo,
        env.ISSUE_NUMBER,
        "agent-waiting-human",
      );
    } catch (error) {
      console.warn("Failed to add agent-waiting-human label:", error);
    }

    await postYoloIssueComment(octokit, owner, repo, env.ISSUE_NUMBER, {
      riskLevel,
      riskJustification,
      prLine: `Pull request [#${pr.number}](${pr.url}) created.`,
      phaseReport,
      session,
      runFriction,
    });

    try {
      await manageRiskLabels(octokit, owner, repo, env.ISSUE_NUMBER, riskLevel);
      await manageRiskLabels(octokit, owner, repo, pr.number, riskLevel);
    } catch (error) {
      console.warn("Failed to manage risk labels:", error);
    }

    console.log(`\nPR created: ${pr.url}`);
  } catch (error) {
    await reportPhaseFailure(
      octokit,
      owner,
      repo,
      { kind: "issue", number: env.ISSUE_NUMBER },
      "yolo",
      error,
    );
    throw error;
  }
}

const env = loadAgentEnv();
const { owner, repo } = parseRepository(env.GITHUB_REPOSITORY);
const octokit = createOctokit(env.GITHUB_TOKEN);

runAgentMain(() =>
  runAgentPhase({
    phase: "yolo",
    octokit,
    owner,
    repo,
    issueNumber: env.ISSUE_NUMBER,
    main,
  }),
);
