import {
  YOLO_MODEL,
  loadAgentConfig,
  loadAgentEnv,
  parseRepository,
} from "./config.js";
import {
  applyCommandGithubTools,
  prepareCommandRuntime,
} from "./command-runtime.js";
import {
  checkoutExistingBranch,
  createAndCheckoutBranch,
  resolveYoloBranchName,
} from "./git/branch.js";
import {
  commitAndPushBranch,
  createPullRequest,
  findOpenPullRequestForBranch,
} from "./git/pr.js";
import { buildAgentPrBody } from "./pr-body.js";
import { reportPhaseFailure } from "./report-failure.js";
import {
  appendRunFrictionStepSummary,
  createRunFrictionCollector,
} from "./run-friction.js";
import { runAgentMain, runAgentSession } from "./runtime.js";
import { runAgentPhase } from "./lifecycle.js";
import {
  addLabelToIssue,
  AGENT_COMMENT_MARKERS,
  buildRunUrl,
  createOctokit,
  ensureLabel,
  extractRiskJustification,
  findPlanCommentUrl,
  manageRiskLabels,
  parseRiskLevel,
  postComment,
  prependAgentMarker,
  readComments,
  readIssue,
} from "./tools/github.js";
import { createAgentTools } from "./tools/index.js";
import { gitStatusPorcelainExcludingPipelineCheckoutCommand } from "./git/worktree-excludes.js";
import {
  commitsAheadOfBaseCommand,
  shouldWarnNoYoloChanges,
} from "./git/worktree-status.js";
import { runShell } from "./tools/shell.js";
import { withReportRunFrictionTool } from "./tools/run-friction-tool.js";
import {
  appendSubmitPhaseReportTool,
  createPhaseReportTracker,
  formatPhaseCompletionMarkdown,
  formatPhaseReportForPr,
  formatRunMetricsMarkdown,
  type PhaseReport,
} from "./phase-report.js";
import type { AgentSessionResult } from "./runtime.js";
import type { RunFrictionCollector } from "./run-friction.js";
import type { RiskLevel } from "./tools/github.js";

function resolveYoloRiskAssessment(
  phaseReport: PhaseReport | undefined,
  outputText: string,
): { riskLevel: RiskLevel; riskJustification: string } {
  if (phaseReport?.riskLevel && phaseReport.riskJustification) {
    return {
      riskLevel: phaseReport.riskLevel,
      riskJustification: phaseReport.riskJustification,
    };
  }

  const parsedRiskLevel = parseRiskLevel(outputText);
  if (!parsedRiskLevel) {
    console.warn(
      "Could not parse risk level from yolo output; defaulting to medium.",
    );
  }
  return {
    riskLevel: parsedRiskLevel ?? "medium",
    riskJustification:
      extractRiskJustification(outputText) ??
      "Risk assessment generated by the yolo agent.",
  };
}

async function postYoloIssueComment(
  octokit: ReturnType<typeof createOctokit>,
  owner: string,
  repo: string,
  issueNumber: number,
  params: {
    riskLevel: string;
    riskJustification: string;
    prLine: string;
    phaseReport: PhaseReport | undefined;
    session: AgentSessionResult;
    runFriction: RunFrictionCollector;
  },
): Promise<void> {
  const implementComment = [
    `## Agent Implementation`,
    "",
    `**Risk score:** ${params.riskLevel} — ${params.riskJustification}`,
    "",
    params.prLine,
    "",
    formatPhaseCompletionMarkdown({
      phase: "yolo",
      phaseReport: params.phaseReport,
      sessionUsage: params.session.usage,
      sessionId: params.session.sessionId,
      modelId: params.session.modelId,
      servedModelIds: params.session.servedModelIds,
      openRouterCostUsd: params.session.openRouterCostUsd,
      iterations: params.session.iterations,
      toolCallsCount: params.session.toolCallsCount,
      runFriction: params.runFriction,
    }),
  ].join("\n\n");

  await postComment(
    octokit,
    owner,
    repo,
    issueNumber,
    prependAgentMarker(implementComment, AGENT_COMMENT_MARKERS.yolo),
  );
}

async function applyYoloRiskLabels(
  octokit: ReturnType<typeof createOctokit>,
  owner: string,
  repo: string,
  issueNumber: number,
  prNumber: number,
  riskLevel: RiskLevel,
): Promise<void> {
  try {
    await manageRiskLabels(octokit, owner, repo, issueNumber, riskLevel);
    await manageRiskLabels(octokit, owner, repo, prNumber, riskLevel);
  } catch (error) {
    console.warn("Failed to manage risk labels:", error);
  }
}

async function main() {
  const env = loadAgentEnv();
  const config = loadAgentConfig();
  const cmd = prepareCommandRuntime("yolo", YOLO_MODEL, config);
  const { owner, repo } = parseRepository(env.GITHUB_REPOSITORY);
  const octokit = createOctokit(env.GITHUB_TOKEN);

  try {
    const issue = await readIssue(octokit, owner, repo, env.ISSUE_NUMBER);

    const branch = resolveYoloBranchName(
      env.ISSUE_NUMBER,
      issue.title,
      env.AGENT_BRANCH,
      config.git.branch_prefix,
    );
    if (env.AGENT_BRANCH) {
      await checkoutExistingBranch(branch);
    } else {
      await createAndCheckoutBranch(branch, config.git.base_branch);
    }

    const runFriction = createRunFrictionCollector();
    const phaseReportTracker = createPhaseReportTracker();
    let tools = await withReportRunFrictionTool(
      await appendSubmitPhaseReportTool(
        await createAgentTools(octokit, owner, repo, env.ISSUE_NUMBER),
        phaseReportTracker,
        { requireRiskAssessment: true },
      ),
      runFriction,
    );
    tools = applyCommandGithubTools(tools, cmd.resolved.tools.github);

    const userArgs = process.env.AGENT_COMMAND_ARGS?.trim();
    const extraArgsBlock = userArgs
      ? `\n\nAdditional instructions:\n${userArgs}`
      : "";

    const session = await runAgentSession({
      phase: cmd.runtimePhase,
      modelId: cmd.modelId,
      systemPrompt: cmd.systemPrompt,
      tools,
      runFriction,
      sessionMetadata: {
        phase: cmd.runtimePhase,
        commandId: cmd.commandId,
        issueNumber: env.ISSUE_NUMBER,
        repository: env.GITHUB_REPOSITORY,
        branch,
      },
      prompt: `Implement issue #${env.ISSUE_NUMBER}: ${issue.title}

Issue body (implementation instructions):
${issue.body ?? "(empty)"}

Repository: ${env.GITHUB_REPOSITORY}
Branch: ${branch}${extraArgsBlock}`,
    });

    appendRunFrictionStepSummary(runFriction, "yolo");

    const phaseReport = phaseReportTracker.report;
    const phaseReportMarkdown = phaseReport
      ? formatPhaseReportForPr(phaseReport)
      : undefined;

    const { riskLevel, riskJustification } = resolveYoloRiskAssessment(
      phaseReport,
      session.outputText,
    );

    if (phaseReport?.summary) {
      const worktreeStatus = await runShell(
        gitStatusPorcelainExcludingPipelineCheckoutCommand(),
      );
      // `git status --porcelain` only compares the index/worktree to HEAD, so a
      // session that committed its own work shows a clean tree while still
      // being ahead of the base branch. Count the commits ahead too, otherwise
      // the warning below would fire on every already-committed re-run.
      const ahead = await runShell(
        commitsAheadOfBaseCommand(config.git.base_branch),
      );
      if (shouldWarnNoYoloChanges(worktreeStatus, ahead)) {
        console.warn(
          `yolo: submitPhaseReport was called but there are no changes vs origin/${config.git.base_branch} (clean working tree, no commits ahead)`,
        );
      }
    }

    const pushResult = await commitAndPushBranch(
      branch,
      `feat: implement issue #${env.ISSUE_NUMBER} — ${issue.title}`,
      { baseBranch: config.git.base_branch },
    );

    if (pushResult.status === "noChanges") {
      const existingPr = await findOpenPullRequestForBranch(branch);
      if (!existingPr) {
        throw new Error(
          `No changes detected and no open pull request exists for branch ${branch}.`,
        );
      }

      const prLine = `No new commits were needed; work is already tracked in pull request [#${existingPr.number}](${existingPr.url}).`;

      await postYoloIssueComment(octokit, owner, repo, env.ISSUE_NUMBER, {
        riskLevel,
        riskJustification,
        prLine,
        phaseReport,
        session,
        runFriction,
      });

      await applyYoloRiskLabels(
        octokit,
        owner,
        repo,
        env.ISSUE_NUMBER,
        existingPr.number,
        riskLevel,
      );

      console.log(
        `\nYolo completed with no changes on branch ${branch} (PR #${existingPr.number})`,
      );
      return;
    }

    if (cmd.resolved.git?.skip_pr) {
      console.log("\nSkipping PR creation (commands.git.skip_pr).");
      return;
    }

    const comments = await readComments(octokit, owner, repo, env.ISSUE_NUMBER);

    const usageSection = formatRunMetricsMarkdown(session, {
      collapsible: true,
    });

    const pr = await createPullRequest(
      issue.title,
      buildAgentPrBody({
        issueNumber: env.ISSUE_NUMBER,
        issueTitle: issue.title,
        issueUrl: issue.html_url,
        planCommentUrl: findPlanCommentUrl(comments),
        usageMarkdown: usageSection,
        riskLevel,
        riskJustification,
        phaseReportMarkdown,
      }),
      branch,
      config.git.pr_target,
    );

    await addLabelToIssue(octokit, owner, repo, pr.number, "agent-pr");

    const runUrl = buildRunUrl();
    const prOpenedBody = `PR opened by this run — ${runUrl ? `[View in GitHub Actions](${runUrl})` : "run URL unavailable"}`;
    await postComment(
      octokit,
      owner,
      repo,
      pr.number,
      prependAgentMarker(prOpenedBody, AGENT_COMMENT_MARKERS.prOpened),
    );

    try {
      await ensureLabel(octokit, owner, repo, "agent-waiting-human", {
        color: "f9d0c4",
        description: "Waiting for human decision on this issue.",
      });
      await addLabelToIssue(
        octokit,
        owner,
        repo,
        env.ISSUE_NUMBER,
        "agent-waiting-human",
      );
    } catch (error) {
      console.warn("Failed to add agent-waiting-human label:", error);
    }

    await postYoloIssueComment(octokit, owner, repo, env.ISSUE_NUMBER, {
      riskLevel,
      riskJustification,
      prLine: `Pull request [#${pr.number}](${pr.url}) created.`,
      phaseReport,
      session,
      runFriction,
    });

    await applyYoloRiskLabels(
      octokit,
      owner,
      repo,
      env.ISSUE_NUMBER,
      pr.number,
      riskLevel,
    );

    console.log(`\nPR created: ${pr.url}`);
  } catch (error) {
    await reportPhaseFailure(
      octokit,
      owner,
      repo,
      { kind: "issue", number: env.ISSUE_NUMBER },
      "yolo",
      error,
    );
    throw error;
  }
}

const env = loadAgentEnv();
const { owner, repo } = parseRepository(env.GITHUB_REPOSITORY);
const octokit = createOctokit(env.GITHUB_TOKEN);
const bootCmd = prepareCommandRuntime("yolo", YOLO_MODEL, loadAgentConfig());

runAgentMain(() =>
  runAgentPhase({
    phase: bootCmd.runtimePhase,
    displayLabel: bootCmd.displayLabel,
    octokit,
    owner,
    repo,
    issueNumber: env.ISSUE_NUMBER,
    main,
  }),
);
