import { describe, expect, it, vi } from "vitest";
import {
  resolveYoloRiskAssessment,
  resolveYoloRiskSourceOutput,
} from "./yolo-risk.js";

describe("resolveYoloRiskSourceOutput", () => {
  it("returns the last session output when it carries a risk assessment", () => {
    expect(
      resolveYoloRiskSourceOutput([
        { outputText: "### Risk score:\nhigh\n\nDone." },
        { outputText: "### Risk score:\nlow\n\nDone." },
      ]),
    ).toBe("### Risk score:\nlow\n\nDone.");
  });

  it("keeps the implementation session risk when a hook retry has none", () => {
    const implementation = "Implemented the fix.\n\nrisk: high";
    const hookRetry = "Fixed the lint error reported by the commit hook.";
    expect(
      resolveYoloRiskSourceOutput([
        { outputText: implementation },
        { outputText: hookRetry },
      ]),
    ).toBe(implementation);
  });

  it("falls back to the last session output when no risk is parseable", () => {
    expect(
      resolveYoloRiskSourceOutput([
        { outputText: "no risk here" },
        { outputText: "still nothing" },
      ]),
    ).toBe("still nothing");
  });

  it("returns an empty string for no sessions", () => {
    expect(resolveYoloRiskSourceOutput([])).toBe("");
  });
});

describe("resolveYoloRiskAssessment", () => {
  it("prefers the phase report when present", () => {
    expect(
      resolveYoloRiskAssessment(
        {
          summary: "Implemented the feature.",
          riskLevel: "high",
          riskJustification: "Touches auth.",
        },
        "risk: low",
      ),
    ).toEqual({ riskLevel: "high", riskJustification: "Touches auth." });
  });

  it("parses the risk level from the session output", () => {
    expect(resolveYoloRiskAssessment(undefined, "risk: low")).toEqual({
      riskLevel: "low",
      riskJustification: "Risk assessment generated by the yolo agent.",
    });
  });

  it("warns and defaults to medium when nothing parses", () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => undefined);
    try {
      expect(resolveYoloRiskAssessment(undefined, "nothing here")).toEqual({
        riskLevel: "medium",
        riskJustification: "Risk assessment generated by the yolo agent.",
      });
      expect(warn).toHaveBeenCalledWith(
        "Could not parse risk level from yolo output; defaulting to medium.",
      );
    } finally {
      warn.mockRestore();
    }
  });
});
